version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - automerge
    groups:
      root-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /apps/pulse/hosted/ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - automerge
    groups:
      pulse-ui-deps:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /apps/synthr/server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - automerge
    groups:
      synthr-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - automerge
