import React, { useState } from 'react'
import { 
  MessageSquare, Bot, PenLine, Brain, BarChart3, Settings, Plus, 
  Image as ImageIcon, TrendingUp, ShieldCheck, Fingerprint, Coins, 
  Send, User, ChevronDown, Check 
} from 'lucide-react'

/**
 * Pulse v3 / modern standalone — Full interactive mock for Replit web mock display.
 * Based on the complete version from pulse.zip (hosted/ui).
 * Includes:
 *  - Sidebar with multi-agent / brand switcher
 *  - Chat / chat-setup screen (default landing)
 *  - Settings with Agents tab (the multi-agent management)
 *  - Activity, Media, Create quick views (tab switchable)
 * Fully client-side with realistic interactions.
 */

type View = 'chat' | 'settings' | 'activity' | 'media' | 'create'

interface Agent {
  id: string
  name: string
  brandName: string
  niche: string
}

const initialAgents: Agent[] = [
  { id: 'default', name: 'Acme Labs', brandName: 'Acme Labs', niche: 'devtools' },
  { id: 'bakery', name: 'Sweet Treats', brandName: 'Sweet Treats Bakery', niche: 'food & beverage' },
]

export default function PulseFullAppMock() {
  const [currentView, setCurrentView] = useState<View>('chat')
  const [agents, setAgents] = useState<Agent[]>(initialAgents)
  const [activeAgentId, setActiveAgentId] = useState('default')
  const [chatMessages, setChatMessages] = useState([
    { id: 1, role: 'assistant' as const, text: 'Hi! I\'m your Pulse agent crew. What are we launching or optimizing today?' },
  ])
  const [chatInput, setChatInput] = useState('')
  const [activity, setActivity] = useState([
    { id: '1', type: 'post', platform: 'x', text: 'Shipped new multi-agent tab — the team is loving the presets.', time: '14m ago' },
    { id: '2', type: 'reply', platform: 'x', text: 'Thanks for the feedback on the strategy doc!', time: '1h ago' },
  ])
  const [mediaItems, setMediaItems] = useState([
    { id: 'm1', name: 'product-hero.png', tag: 'launch' },
    { id: 'm2', name: 'team-offsite.jpg', tag: 'brand' },
  ])
  const [newAgentName, setNewAgentName] = useState('')
  const [settingsTab, setSettingsTab] = useState<'agents' | 'general' | 'voice'>('agents')

  const activeAgent = agents.find(a => a.id === activeAgentId) || agents[0]

  const switchAgent = (id: string) => {
    setActiveAgentId(id)
    // simulate context switch toast
    setChatMessages(prev => [...prev, { 
      id: Date.now(), 
      role: 'assistant', 
      text: `Switched to ${agents.find(a=>a.id===id)?.brandName}. All future actions use this brand DNA.` 
    }])
  }

  const createAgent = () => {
    if (!newAgentName.trim()) return
    const newA: Agent = {
      id: 'agent-' + Date.now(),
      name: newAgentName.trim(),
      brandName: newAgentName.trim(),
      niche: 'custom'
    }
    setAgents(prev => [...prev, newA])
    setActiveAgentId(newA.id)
    setNewAgentName('')
    setChatMessages(prev => [...prev, { 
      id: Date.now(), 
      role: 'assistant', 
      text: `New agent preset "${newA.brandName}" created. You can now use the multi-agent crew for this brand.` 
    }])
  }

  const sendChat = () => {
    if (!chatInput.trim()) return
    const userMsg = { id: Date.now(), role: 'user' as const, text: chatInput.trim() }
    setChatMessages(prev => [...prev, userMsg])
    const val = chatInput.trim().toLowerCase()
    setChatInput('')

    setTimeout(() => {
      let reply = "Understood. I've briefed the Strategist and Content Creator agents. Previewing 3 post variants + a thread in the Create tab."
      if (val.includes('agent') || val.includes('multi')) {
        reply = "The multi-agent system is running. Current crew: Strategist, Content, Analyst, Community. Switch brands in the sidebar."
      } else if (val.includes('post') || val.includes('launch')) {
        reply = "Campaign brief accepted. 6 posts scheduled. Ready for human approval gates."
      }
      setChatMessages(prev => [...prev, { id: Date.now() + 1, role: 'assistant' as const, text: reply }])
    }, 650)
  }

  const addToActivity = () => {
    const newItem = {
      id: 'act' + Date.now(),
      type: 'post',
      platform: 'x',
      text: 'New content generated by the crew for ' + activeAgent.brandName,
      time: 'just now'
    }
    setActivity(prev => [newItem, ...prev])
    setCurrentView('activity')
  }

  return (
    <div style={{ display: 'flex', height: '100vh', background: '#0a0a0b', color: '#fff', fontFamily: 'Inter, system-ui, sans-serif' }}>
      {/* Sidebar - shows multi-agent switcher */}
      <div style={{ width: 260, background: '#111113', borderRight: '1px solid #222', display: 'flex', flexDirection: 'column' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid #222', display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 28, height: 28, background: 'linear-gradient(135deg,#3b82f6,#8b5cf6)', borderRadius: 6 }} />
          <div>
            <div style={{ fontWeight: 700, fontSize: 18 }}>Pulse</div>
            <div style={{ fontSize: 10, color: '#888' }}>v3 • modern</div>
          </div>
        </div>

        {/* Agent / Multi-agent switcher */}
        <div style={{ padding: '12px 16px' }}>
          <div style={{ fontSize: 11, color: '#777', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '.5px' }}>Active Agent (Multi-agent)</div>
          {agents.map(a => (
            <div 
              key={a.id}
              onClick={() => switchAgent(a.id)}
              style={{
                padding: '8px 10px',
                marginBottom: 4,
                borderRadius: 8,
                background: activeAgentId === a.id ? '#1f2937' : 'transparent',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                border: activeAgentId === a.id ? '1px solid #3b82f6' : '1px solid transparent'
              }}
            >
              <Bot size={15} />
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 13, fontWeight: 600 }}>{a.brandName}</div>
                <div style={{ fontSize: 11, color: '#666' }}>{a.niche}</div>
              </div>
              {activeAgentId === a.id && <Check size={14} color="#3b82f6" />}
            </div>
          ))}

          {/* Create new agent */}
          <div style={{ marginTop: 10, display: 'flex', gap: 6 }}>
            <input 
              value={newAgentName} 
              onChange={e => setNewAgentName(e.target.value)}
              placeholder="New brand preset"
              style={{ flex: 1, background: '#1a1a1c', border: '1px solid #333', color: '#fff', padding: '6px 8px', borderRadius: 6, fontSize: 12 }}
              onKeyDown={e => e.key === 'Enter' && createAgent()}
            />
            <button onClick={createAgent} style={{ padding: '6px 10px', background: '#3b82f6', border: 'none', borderRadius: 6, color: '#fff', cursor: 'pointer' }}>
              <Plus size={15} />
            </button>
          </div>
        </div>

        <div style={{ padding: '8px 16px', fontSize: 11, color: '#555', marginTop: 8 }}>NAVIGATION</div>
        <nav style={{ padding: '0 8px' }}>
          {[
            { v: 'chat' as const, label: 'Chat / Setup', icon: MessageSquare },
            { v: 'create' as const, label: 'Create', icon: PenLine },
            { v: 'activity' as const, label: 'Activity', icon: BarChart3 },
            { v: 'media' as const, label: 'Media', icon: ImageIcon },
            { v: 'settings' as const, label: 'Settings', icon: Settings },
          ].map(item => {
            const Icon = item.icon
            const active = currentView === item.v
            return (
              <div 
                key={item.v}
                onClick={() => setCurrentView(item.v)}
                style={{ 
                  padding: '9px 12px', 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: 9, 
                  borderRadius: 8, 
                  margin: '2px 8px',
                  background: active ? '#1f2937' : 'transparent',
                  cursor: 'pointer',
                  fontSize: 13 
                }}
              >
                <Icon size={16} /> {item.label}
              </div>
            )
          })}
        </nav>

        <div style={{ marginTop: 'auto', padding: 16, fontSize: 11, color: '#555', borderTop: '1px solid #222' }}>
          Credits: 1,240 &nbsp;•&nbsp; Agent crew active
        </div>
      </div>

      {/* Main content area */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        {/* Top bar */}
        <div style={{ height: 52, borderBottom: '1px solid #222', display: 'flex', alignItems: 'center', padding: '0 20px', gap: 12, background: '#0f0f11' }}>
          <div style={{ fontWeight: 600 }}>{activeAgent.brandName}</div>
          <div style={{ fontSize: 12, padding: '1px 8px', background: '#222', borderRadius: 999 }}>multi-agent mode</div>
          <div style={{ marginLeft: 'auto', fontSize: 12, color: '#777' }}>localhost mock • complete v3</div>
        </div>

        {/* Views */}
        <div style={{ flex: 1, overflow: 'auto', padding: 24 }}>
          {currentView === 'chat' && (
            <div style={{ maxWidth: 720 }}>
              <h2 style={{ fontSize: 22, marginBottom: 8 }}>Chat Setup</h2>
              <p style={{ color: '#888', marginBottom: 20 }}>Talk to the crew. This is the primary modern entry point.</p>

              <div style={{ background: '#111', borderRadius: 12, padding: 16, minHeight: 260, display: 'flex', flexDirection: 'column' }}>
                <div style={{ flex: 1, overflowY: 'auto', marginBottom: 12 }}>
                  {chatMessages.map(m => (
                    <div key={m.id} style={{ display: 'flex', gap: 10, marginBottom: 12 }}>
                      {m.role === 'assistant' ? <Bot /> : <User />}
                      <div style={{ background: m.role === 'assistant' ? '#1a1a1c' : '#222', padding: '8px 12px', borderRadius: 8, maxWidth: '80%' }}>
                        {m.text}
                      </div>
                    </div>
                  ))}
                </div>
                <div style={{ display: 'flex', gap: 8 }}>
                  <input 
                    value={chatInput} 
                    onChange={e => setChatInput(e.target.value)} 
                    onKeyDown={e => e.key === 'Enter' && sendChat()}
                    placeholder="Tell Pulse what to do (e.g. launch campaign with multi-agent)" 
                    style={{ flex: 1, background: '#1a1a1c', border: '1px solid #333', color: 'white', padding: '10px 14px', borderRadius: 8 }}
                  />
                  <button onClick={sendChat} style={{ padding: '0 18px', background: '#3b82f6', borderRadius: 8, border: 'none', color: 'white' }}><Send size={16} /></button>
                </div>
              </div>
              <div style={{ fontSize: 12, color: '#555', marginTop: 12 }}>Tip: switch agents in the left sidebar to use different brand DNA.</div>
            </div>
          )}

          {currentView === 'settings' && (
            <div style={{ maxWidth: 820 }}>
              <h2 style={{ fontSize: 22, marginBottom: 16 }}>Settings</h2>

              <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
                {(['agents', 'general', 'voice'] as const).map(t => (
                  <button key={t} onClick={() => setSettingsTab(t)} className="btn-tab" style={{ padding: '6px 16px', borderRadius: 999, background: settingsTab === t ? '#3b82f6' : '#222', color: '#fff', border: 'none' }}>
                    {t === 'agents' ? 'Agents (Multi-Agent)' : t}
                  </button>
                ))}
              </div>

              {settingsTab === 'agents' && (
                <div>
                  <div style={{ marginBottom: 12, color: '#888' }}>Agent presets — the core of the multi-agent system. Each preset carries its own brand DNA, voice, topics and competitors.</div>
                  {agents.map(a => (
                    <div key={a.id} style={{ background: '#111', padding: 16, borderRadius: 10, marginBottom: 8, display: 'flex', justifyContent: 'space-between' }}>
                      <div>
                        <div style={{ fontWeight: 600 }}>{a.brandName}</div>
                        <div style={{ fontSize: 13, color: '#777' }}>niche: {a.niche}</div>
                      </div>
                      <button onClick={() => switchAgent(a.id)} style={{ padding: '4px 12px', fontSize: 12, background: '#222', borderRadius: 6, border: '1px solid #444' }}>Activate</button>
                    </div>
                  ))}
                  <div style={{ marginTop: 20, padding: 16, background: '#111', borderRadius: 10 }}>
                    <div style={{ fontWeight: 600, marginBottom: 8 }}>Create new agent preset</div>
                    <input value={newAgentName} onChange={e=>setNewAgentName(e.target.value)} placeholder="Brand name" style={{ background: '#1a1a1c', color: '#fff', padding: 8, width: 240, borderRadius: 6, marginRight: 8 }} />
                    <button onClick={createAgent} style={{ padding: '8px 16px', background: '#3b82f6', borderRadius: 6, border: 'none', color: '#fff' }}>Create + Switch</button>
                  </div>
                </div>
              )}

              {settingsTab !== 'agents' && <div style={{ color: '#777' }}>Other settings sections (General / Voice calibration) would live here in the full version.</div>}
            </div>
          )}

          {currentView === 'activity' && (
            <div>
              <h2>Activity</h2>
              <div style={{ marginTop: 12 }}>
                {activity.map(item => (
                  <div key={item.id} style={{ background: '#111', padding: 14, borderRadius: 8, marginBottom: 8 }}>
                    <div style={{ fontSize: 12, color: '#777' }}>{item.time} • {item.platform}</div>
                    <div>{item.text}</div>
                  </div>
                ))}
              </div>
              <button onClick={addToActivity} style={{ marginTop: 12, padding: '8px 14px', background: '#222', borderRadius: 6 }}>Simulate new post from crew</button>
            </div>
          )}

          {currentView === 'media' && (
            <div>
              <h2>Media Library</h2>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px,1fr))', gap: 12, marginTop: 16 }}>
                {mediaItems.map(m => (
                  <div key={m.id} style={{ background: '#111', padding: 8, borderRadius: 8 }}>
                    <div style={{ height: 100, background: '#222', borderRadius: 4, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#555' }}>IMG</div>
                    <div style={{ fontSize: 12, marginTop: 6 }}>{m.name} <span style={{ color: '#666' }}>· {m.tag}</span></div>
                  </div>
                ))}
              </div>
              <div style={{ marginTop: 20, fontSize: 12, color: '#666' }}>Upload / generate images would be here. Used by the Content Creator agent.</div>
            </div>
          )}

          {currentView === 'create' && (
            <div style={{ maxWidth: 620 }}>
              <h2>Create</h2>
              <p>One-click multi-agent generation for {activeAgent.brandName}.</p>
              <button onClick={addToActivity} style={{ marginTop: 16, padding: '10px 22px', background: '#3b82f6', color: 'white', borderRadius: 8, border: 'none', fontWeight: 600 }}>
                Generate campaign with agents
              </button>
              <div style={{ marginTop: 30, fontSize: 13, color: '#777' }}>
                In the real app this would stream live agent thoughts (Strategist → Content → Analyst) and land in approval gates.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
